export const RoutesUrl = {
    HOME: "/",
    SCHEDULING: "/Scheduling",
    CONFIGURATION: "/Configuration",
    ANALYSIS: "/Analysis",
    DATABRICKS: "/Databricks",
    CREATE_EXPERIMENTS: "/create-experiments",
    CREATE_MAPPINGS: "/create-mappings",
    INSIGHT: "/insight",
    DATA_INGEST: "/data-ingest",
    UNAUTHORIZED: "/unauthorized",
    TABLE_BASED: "/data-ingest/table",
    SQL_BASED: "/data-ingest/sql",
    STREAM_BASED: "/data-ingest/stream",
    FILE_BASED: "/data-ingest/file",
    CONFORM_CONFIG: "/data-ingest/conform-config",
    HYBRID_CONFIG: "/data-ingest/hybrid-config",
    ADD_NEW_TABLE: "/data-ingest/table/add-table",
    ADD_NEW_ATTRIBUTE: "/data-ingest/table/add-attribute",
    CONFIGURE_EXISTING_TABLE: "/data-ingest/table/configure-table"
}